const fieldNames= [
    "ExternalCause",
    "Inner cause",
    "APN In Used",
    "APN NI",
    "APN NI in used",
    "APN Request by MS",
    "Authentication Flag",
    "Bearer ID",
    "BSSID",
    "CI",
    "CUR TAC",
    "DelayTime",
    "eNB ID",
    "EPS attach result",
    "GGSN Address for signalling",
    "GGSN Address for user traffic",
    "Handover Cancel Phase",
    "IMEI check Flag",
    "IMEISV",
    "Init proc cause",
    "Internal Physical Location",
    "LAC",
    'Message Type',
    "MSISDN",
    "New GUTI MMEC",
    "New GUTI MMEGI",
    "Old GUTI MMEC",
    "Old GUTI MMEGI",
    "Old LAC",
    "Old RAC",
    "Old TAC",
    'PDN Address in used',
    'PDN Gateway Address',
    "PDN Type",
    "PDP address in use",
    "PDP type in used",
    'PDP type request by MS',
    "Peer SGSN Address",
    "QCI",
    "RAC",
    "RNC ID",
    "S1-U eNodeB Address1",
    "S1-U Serving Gateway Address1",
    "Serving Gateway Address",
    "SGS RePaging Count",
    "SGW Change Flag",
    "SRVCC Cause",
    "SRVCC Preparation Period",
    "State MachineName",
    "Target RNC ID",
    "Target TAC",
    "Traffic Class",
    "User Home PLMN",
    "VLR No",
    "Voice domain preference and UE's usage setting"
]